# Generated by Django 4.1.4 on 2023-03-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_comments_posts_userprofile_delete_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='caption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='upvote',
            field=models.ManyToManyField(related_name='Liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='posts',
            name='upvote',
            field=models.ManyToManyField(related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
